Add "product" and "category" content types
Voog/voog-kit pull request #58
Opened 2021-12-20 07:39 UTC by pxska

Additionally, if the content type doesn't exist in the given `preferred_order` array, sort the layout to the end of the `manifest.json` file.

Closes #56.

2021-12-20 09:03 UTC, tanelj approved these changes

2021-12-20 13:27 UTC, tambeta requested changes

2021-12-20 13:27 UTC, tambeta commented on lib/voog/dtk/filemanager.rb
> +        (preferred_order.index(a.fetch('content_type')) <=> preferred_order.index(b.fetch('content_type'))) || 1
See ei tööta PR kirjelduses välja reklaamitud kujul (eeldan, et pead siin silmas `layouts` struktuuri lõppu sorteerimist):

>Additionally, if the content type doesn't exist in the given `preferred_order` array, sort the layout to the end of the `manifest.json` file.

Nt konstrueerides struktuur:

```
layouts = [
  {                                  
    "content_type" => "product",     
  },                                 
  {                                  
    "content_type" => "page",        
  },                                 
  {                                  
    "content_type" => "blog_article",
  },                                 
  {                                  
    "content_type" => "blog",        
  },                                 
  {                                  
    "content_type" => "ding",
  },                                 
  {                                  
    "content_type" => "dong",        
  },                                 
]                                    
```

on tulemus:

```
  "layouts": [
    {
      "content_type": "ding"
    },
    {
      "content_type": "dong"
    },
    {
      "content_type": "page"
    },
    {
      "content_type": "blog"
    },
    {
      "content_type": "blog_article"
    },
    {
      "content_type": "product"
    }
  ]
```

Peaks olema:

```suggestion
      type_index = ->(e) { preferred_order.index(e['content_type']) || Float::INFINITY }
                                                                                        
      layouts.sort { |a, b| type_index[a] <=> type_index[b] }
```

Ühtlasi peaks see meetod `private` olema.

2021-12-20 18:22 UTC, tambeta requested changes

2021-12-20 18:22 UTC, tambeta commented on lib/voog/dtk/filemanager.rb
> +          manifest[k].sort! { |a, b| a["file"] <=> b["file"] }
Võiks garanteerida, et õhku ei lenda. Kui `'file'` võti ühel võrreldavatest puudub, siis annab `<=>` tagasi `nil` ja `sort!` feilib. 

```suggestion
           manifest[k].sort! { |a, b| a["file"] <=> b["file"] || 0 }
```

Pisidetail: kui interpolatsiooni ei kasuta, siis üldiselt on Rubys _string literal_ puhul kombeks `'single quotes'`.

2021-12-21 06:35 UTC, tanelj approved these changes

2021-12-21 06:37 UTC, merged